version: "3"
services:
  db:
    image: postgres:14.2-alpine
    container_name: "db"
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: nestjs
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - db_volume_nestjs:/var/lib/postgresql/data

volumes:
  db_volume_nestjs:
    driver: local