import { Box, Heading } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { ListArticle } from "./components/article/ListArticle";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box m={2}>
        <Heading size="2xl">Blog with Next.js, GraphQL</Heading>
      </Box>

      <Box m={2}>
        <Heading mb={2} size="lg">
          Articles
        </Heading>
        <ListArticle />
      </Box>
    </div>
  );
};

export default Home;
